import Foundation
import DexmoClientLibrary

public class Container {
    public var VisitLogOperationDetailInformation_Operations: Operation?
    public var VisitLogOperationDetailInformation: VisitLogOperationDetailInformation?
    public var AccountBalance_DynamicFields: AccountBalanceDynamicField?
    public var AccountBalance_MonthlyBalances: MonthlyBalance?
    public var AccountBalance: AccountBalance?
    public var ServiceOrderFiles_Files: ServiceOrderFile?
    public var ServiceOrderFiles: ServiceOrderFiles?
    public var ProductGroup: ProductGroup?
    public var PhysicalStockCount_DynamicFields: PhysicalCountDynamicField?
    public var PhysicalStockCount_Lines_SerialCodes: PyhsicalCountSerialCode?
    public var PhysicalStockCount_Lines: PhysicalStockCountLine?
    public var PhysicalStockCount: PhysicalStockCount?
    public var PurchaseOrder_AdditionalTaxTotals: AdditionalTaxAmountOnPurchaseOrder?
    public var PurchaseOrder_DynamicFields: PurchaseOrderDynamicField?
    public var PurchaseOrder_Lines_AdditionalTaxAmounts: PurchaseOrderLineAdditionalTax?
    public var PurchaseOrder_Lines_WorkedCurrenciesInfos: PurchaseOrderLineWorkedCurrencyInfo?
    public var PurchaseOrder_Lines: PurchaseOrderLine?
    public var PurchaseOrder: PurchaseOrder?
    public var Labor_DynamicFields: LaborDynamicField?
    public var Labor_LaborProductGroups_ProductGroups: LaborProductGroup?
    public var Labor_LaborProductGroups: LaborProductGroups?
    public var Labor: Labor?
    public var PurchaseDispatch_AdditionalTaxTotals: AdditionalTaxAmountOnPurchaseDispatch?
    public var PurchaseDispatch_DynamicFields: PurchaseDispatchDynamicField?
    public var PurchaseDispatch_Lines_AdditionalTaxAmounts: PurchaseDispatchLineAdditionalTax?
    public var PurchaseDispatch_Lines_SerialCodes: PurchaseDispatchLineSerialCodes?
    public var PurchaseDispatch_Lines_WorkedCurrenciesInfos: PurchaseDispatchLineWorkedCurrencyInfo?
    public var PurchaseDispatch_Lines: PurchaseDispatchLine?
    public var PurchaseDispatch: PurchaseDispatch?
    public var StockErrorCode_DynamicFields: ErrorCodesDynamicField?
    public var StockErrorCode_ErrorCodeFiles: ErrorCodeFile?
    public var StockErrorCode_Stocks: StockWithError?
    public var StockErrorCode: StockErrorCode?
    public var Brand: Brand?
    public var SalesProposal_AdditionalTaxTotals: AdditionalTaxAmountOnSalesProposal?
    public var SalesProposal_DynamicFields: SalesProposalDynamicField?
    public var SalesProposal_Lines_AdditionalTaxAmounts: SalesProposalLineAdditionalTax?
    public var SalesProposal_Lines_WorkedCurrenciesInfos: SalesProposalLineWorkedCurrencyInfo?
    public var SalesProposal_Lines: SalesProposalLine?
    public var SalesProposal: SalesProposal?
    public var PersonCertificateAndTraning: PersonCertificateAndTraning?
    public var Territory_DynamicFields: TerritoryDynamicField?
    public var Territory: Territory?
    public var AccountVisit_VisitLogs: VisitLog?
    public var AccountVisit: AccountVisit?
    public var Expense_DynamicFields: ExpenseDynamicField?
    public var Expense_ExpenseLines: ExpenseLine?
    public var Expense: Expense?
    public var LaborGroup: LaborGroup?
    public var Dealer_Addresses: AddressInformation?
    public var Dealer_DynamicFields: DealerDynamicField?
    public var Dealer: Dealer?
    public var PersonRoute_DynamicFields: PersonRouteDynamicField?
    public var PersonRoute_Locations: PersonRouteLocation?
    public var PersonRoute: PersonRoute?
    public var CertificatesAndTraning: CertificatesAndTraning?
    public var WarehouseTransaction_DynamicFields: WarehouseTransactionDynamicField?
    public var WarehouseTransaction_Lines_SerialCodes: SerialCode?
    public var WarehouseTransaction_Lines: TransactionLine?
    public var WarehouseTransaction: WarehouseTransaction?
    public var PurchaseInvoice_AdditionalTaxTotals: AdditionalTaxAmountOnPurchaseInvoice?
    public var PurchaseInvoice_DynamicFields: PurchaseInvoiceDynamicField?
    public var PurchaseInvoice_Lines_AdditionalTaxAmounts: PurchaseInvoiceLineAdditionalTax?
    public var PurchaseInvoice_Lines_SerialCodes: PurchaseInvoiceLineSerialCodes?
    public var PurchaseInvoice_Lines_WorkedCurrenciesInfos: PurchaseInvoiceLineWorkedCurrencyInfo?
    public var PurchaseInvoice_Lines: PurchaseInvoiceLine?
    public var PurchaseInvoice: PurchaseInvoice?
    public var EmailTemplates_Variables: Variable?
    public var EmailTemplates: EmailTemplates?
    public var StockLevel_DynamicFields: StockLevelDynamicField?
    public var StockLevel: StockLevel?
    public var DynamicForm_Fields_Annotations: DynamicFormFieldAnnotation?
    public var DynamicForm_Fields: DynamicFormField?
    public var DynamicForm: DynamicForm?
    public var CommercialSettings_AcceptableCurrencies: AcceptableCurrency?
    public var CommercialSettings: CommercialSettings?
    public var Serial_DynamicFields: SerialDynamicField?
    public var Serial_Transactions: SerialTransaction?
    public var Serial: Serial?
    public var AdditionalTax_DynamicFields: AdditionalTaxDynamicField?
    public var AdditionalTax: AdditionalTax?
    public var CreditCardCollection_DynamicFields: CreditCardCollectionDynamicField?
    public var CreditCardCollection_WorkedCurrenciesInfos: CreditCardCollectionWorkedCurrencyInfo?
    public var CreditCardCollection: CreditCardCollection?
    public var SalesInvoice_AdditionalTaxTotals: AdditionalTaxAmountOnSalesInvoice?
    public var SalesInvoice_DynamicFields: SalesInvoiceDynamicField?
    public var SalesInvoice_Lines_AdditionalTaxAmounts: SalesInvoiceLineAdditionalTax?
    public var SalesInvoice_Lines_SerialCodes: SalesInvoiceLineSerialCodes?
    public var SalesInvoice_Lines_WorkedCurrenciesInfos: SalesInvoiceLineWorkedCurrencyInfo?
    public var SalesInvoice_Lines: SalesInvoiceLine?
    public var SalesInvoice: SalesInvoice?
    public var PriceList_DynamicFields: PriceListDynamicField?
    public var PriceList_StockPrices: StockPrice?
    public var PriceList: PriceList?
    public var DynamicFormData_Files: DynamicFormFile?
    public var DynamicFormData: DynamicFormData?
    public var CompanySettings_AcceptableCurrencies: CompanyCurrency?
    public var CompanySettings: CompanySettings?
    public var CurrencyRate: CurrencyRate?
    public var Route_DynamicFields: RouteDynamicField?
    public var Route_Locations: RouteLocation?
    public var Route: Route?
    public var ProductGroupLevel: ProductGroupLevel?
    public var ServiceAndSupportSettings: ServiceAndSupportSettings?
    public var ServiceOrderLabor: ServiceOrderLabor?
    public var Warehouse_DynamicFields: WarehouseDynamicField?
    public var Warehouse: Warehouse?
    public var CashCollection_DynamicFields: CashCollectionDynamicField?
    public var CashCollection_WorkedCurrenciesInfos: CashCollectionWorkedCurrencyInfo?
    public var CashCollection: CashCollection?
    public var ServiceRequest_Files: File?
    public var ServiceRequest_Notes: Note?
    public var ServiceRequest_Stocks: ServiceRequestStock?
    public var ServiceRequest: ServiceRequest?
    public var CalenderEvent_DaysForRepeatOnWeekly: DayForRepeatOnWeekly?
    public var CalenderEvent_DynamicFields: CalenderEventDynamicField?
    public var CalenderEvent: CalenderEvent?
    public var PersonLocation: PersonLocation?
    public var AccountProducts_Stocks: AccountStock?
    public var AccountProducts: AccountProducts?
    public var VisitInformation_DynamicFields: VisitInformationDynamicField?
    public var VisitInformation: VisitInformation?
    public var ServiceOrder_AdditionalTaxTotals: ServiceOrderAdditionalTax?
    public var ServiceOrder_Notes: ServiceOrderNote?
    public var ServiceOrder_Stocks_SpareParts_AdditionalTaxAmounts: SparePartAdditionalTax?
    public var ServiceOrder_Stocks_SpareParts_SerialCodes: SparePartSerialCode?
    public var ServiceOrder_Stocks_SpareParts_WorkedCurrenciesInfos: SparePartWorkedCurrencyInfo?
    public var ServiceOrder_Stocks_SpareParts: ServiceOrderSparePart?
    public var ServiceOrder_Stocks: ServiceOrderStock?
    public var ServiceOrder: ServiceOrder?
    public var PersonWarehouse: PersonWarehouse?
    public var DynamicFormResource_Resources: DynamicFormResourceItem?
    public var DynamicFormResource: DynamicFormResource?
    public var TeamDefinition_DynamicFields: TeamDefinitionDynamicField?
    public var TeamDefinition_TeamMembers: TeamMember?
    public var TeamDefinition: TeamDefinition?
    public var LaborSubGroup: LaborSubGroup?
    public var ExpenseType_DynamicFields: ExpenseTypeDynamicField?
    public var ExpenseType: ExpenseType?
    public var SalesOrder_AdditionalTaxTotals: AdditionalTaxAmountOnSalesOrder?
    public var SalesOrder_DynamicFields: SalesOrderDynamicField?
    public var SalesOrder_Lines_AdditionalTaxAmounts: SalesOrderLineAdditionalTax?
    public var SalesOrder_Lines_WorkedCurrenciesInfos: SalesOrderLineWorkedCurrencyInfo?
    public var SalesOrder_Lines: SalesOrderLine?
    public var SalesOrder: SalesOrder?
    public var Person_DynamicFields: PersonDynamicField?
    public var Person_Educations: Education?
    public var Person_Skills: PersonSkill?
    public var Person: Person?
    public var Shift_DynamicFields: ShiftDynamicField?
    public var Shift_ShiftDaysAndHours_BreakList: Breaks?
    public var Shift_ShiftDaysAndHours: ShiftDayAndHour?
    public var Shift: Shift?
    public var D6F24B41B8C8F3236F56EFBD: DummyDocumentForDbContextConfiguratinon?
    public var Skill_Skills: ExistingSkill?
    public var Skill: Skill?
    public var ServiceOrderForm: ServiceOrderForm?
    public var OrganizationSettings_AcceptableCurrencies: AcceptableCurrency?
    public var OrganizationSettings: OrganizationSettings?
    public var ServiceOrderExpenses_Expenses: ServiceOrderExpense?
    public var ServiceOrderExpenses: ServiceOrderExpenses?
    public var Stock_AdditionalTaxes: AdditionalTaxOnStock?
    public var Stock_DynamicFields: StockDynamicField?
    public var Stock_StockFiles: StockFile?
    public var Stock_StockUnitTypes: StockUnitType?
    public var Stock: Stock?
    public var InventorySettings_AcceptableCurrencies: AcceptableCurrency?
    public var InventorySettings: InventorySettings?
    public var TechnicianBreak: TechnicianBreak?
    public var SalesDispatch_AdditionalTaxTotals: AdditionalTaxAmountOnSalesDispatch?
    public var SalesDispatch_DynamicFields: SalesDispatchDynamicField?
    public var SalesDispatch_Lines_AdditionalTaxAmounts: SalesDispatchLineAdditionalTax?
    public var SalesDispatch_Lines_SerialCodes: SalesDispatchLineSerialCodes?
    public var SalesDispatch_Lines_WorkedCurrenciesInfos: SalesDispatchLineWorkedCurrencyInfo?
    public var SalesDispatch_Lines: SalesDispatchLine?
    public var SalesDispatch: SalesDispatch?
    public var BillOfMaterials_DynamicFields: BillOfMaterialsDynamicField?
    public var BillOfMaterials_EquivalentSpareparts: EquivalentSparepart?
    public var BillOfMaterials_MetarialsFiles: MetarialFile?
    public var BillOfMaterials: BillOfMaterials?
    public var ServiceAndWarrantyAgreement_AgreementFiles: AgreementFile?
    public var ServiceAndWarrantyAgreement_DynamicFields: ServiceAndWarrantyAgreementDynamicField?
    public var ServiceAndWarrantyAgreement_RecurrencePattern: RecurrencePattern?
    public var ServiceAndWarrantyAgreement_Series: StockSerial?
    public var ServiceAndWarrantyAgreement: ServiceAndWarrantyAgreement?
    public var WarrantyOfAccountStock_WarrantyInfoOfStocks: WarrantyInfoOfStock?
    public var WarrantyOfAccountStock: WarrantyOfAccountStock?
    public var Account_Addresses: AddressInfo?
    public var Account_Contacts: ContactInfo?
    public var Account_DynamicFields: AccountDynamicField?
    public var Account_Photos: AccountPhoto?
    public var Account: Account?
}
